services:

  app:
    build: .   # Build locally from Dockerfile in current folder
    container_name: calculator_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://calc:calc@postgres:5432/calculator
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: calculator_db
    environment:
      POSTGRES_USER: calc
      POSTGRES_PASSWORD: calc
      POSTGRES_DB: calculator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: